### ISSUE TITLE
Validating against local schema

### ISSUE THREAD

**Issue by uloco** [shirhatti/SchemaValidator#2]
How can I use this tool for validating a json file against my own local json schema file?
I tried to add `$schema: "filename.json"`, but it didn't work...

The console output is as follows:

```
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/home/uloco/.config/sublime-text-3/Packages/SchemaValidator/SchemaValidator.py", line 119, in run
    request = urllib.request.Request(schema_url, headers={"User-Agent": "Sublime"})
  File "./urllib/request.py", line 275, in __init__
  File "./urllib/request.py", line 280, in _parse
ValueError: unknown url type: 'filename.json'
```

**Comment by shirhatti** [comment]
@uloco There is no support for local schema files, I had not considered it.
You are welcome to implement it as I am not actively involved with the project anymore
